const ACCESS_TOKEN_EXPIRES = process.env.JWT_SECRET_EXPIRES_ACCESS_TOKEN
const REFRESH_TOKEN_EXPIRES = process.env.JWT_SECRET_EXPIRES_REFRESH_TOKEN
const ACCESS_TOKEN_SECRET = process.env.JWT_SECRET_ACCESS_TOKEN
const REFRESH_TOKEN_SECRET = process.env.JWT_SECRET_REFRESH_TOKEN

export default { ACCESS_TOKEN_EXPIRES, REFRESH_TOKEN_EXPIRES, ACCESS_TOKEN_SECRET, REFRESH_TOKEN_SECRET }
