const OAUTH_GOOGLE_CLIENT_ID = process.env.OAUTH_GOOGLE_CLIENT_ID
const OAUTH_GOOGLE_SECRET = process.env.OAUTH_GOOGLE_SECRET
const OAUTH_GOOGLE_REDIRECT_URL = process.env.OAUTH_GOOGLE_REDIRECT_URL

export default { OAUTH_GOOGLE_CLIENT_ID, OAUTH_GOOGLE_SECRET, OAUTH_GOOGLE_REDIRECT_URL }
